### ISSUE TITLE
Connection closure

### ISSUE THREAD

**Issue by DanilKurkin** [erizet/EventSource4Net#4]
Want co confirm that connection closure is not done yet.
using this lib on android and it seems like connection persist even after calling for cxltion token.
Can you please direct me on how disconnection can be achieved?

Thank you

**Comment by DanilKurkin** [comment]
If anyone will come across this brilliant library and try to use it for Xamarin paltform:
There is issue with Android not closing the connection. So I ended up editing WebRequester - added cancelWebRequest methodwhere I do manually abort the connection.

**Comment by erizet** [comment]
Interesting, Can you please send me pull request?
